name: push to azure deops

on:
  pull_request:
    branches:
      - main


jobs:
  build_and_push:
    runs_on: ubuntu_lates
    


    steps:
    - name: checkout repositry 
      uses: actions/checkout@v2

    - name: push to Azure
      run: git remote add azure-devops <https://symtexdev@dev.azure.com/symtexdev/ansible_dock/_git/ansible_dock_GH>
          git push azure-devops HEAD:main