name: Push to Azure DevOps

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push to Azure
        run: |
          git remote add azure-devops "https://symtexdev@dev.azure.com/symtexdev/ansible_dock/_git/ansible_dock_GH"
          git push azure-devops HEAD:main
